const airports = {
    "Aalborg": "AAL",
    "Aarhus": "AAR",
    "Abadan": "ABD",
    "Abakan": "ABA",
    "Aberdeen": "ABR",
    "Aberdeen (UK)": "ABZ",
    "Abha": "AHB",
    "Abu Dhabi": "AUH",
    "Abidjan": "ABJ",
    "Abilene": "ABI",
    "Abuja": "ABV",
    "Acapulco": "ACA",
    "Acarigua": "AGV",
    "Accra": "ACC",
    "Adak Island": "ADK",
    "Adana": "ADA",
    "Addis Ababa": "ADD",
    "Adelaide": "ADL",
    "Aden": "ADE",
    "Adler": "AER",
    "Agadir": "AGA",
    "Aguascaliente": "AGU",
    "Ahmedabad": "AMD",
    "Ajaccio": "AJA",
    "Akiachak": "KKI",
    "Akiak": "AKI",
    "Akita": "AXT",
    "Akron/Canton": "CAK",
    "Al-Baha": "ABT",
    "Al-Fujairah": "FJR",
    "Albany (GA)": "ABY",
    "Albany (NY)": "ALB",
    "Albert Bay": "YAL",
    "Albuquerque": "ABQ",
    "Aleandroupolis": "AXD",
    "Aleppo": "ALP",
    "Alexandria": "ESF",
    "Algiers": "ALG",
    "Alicante": "ALC",
    "Allakaket": "AET",
    "Allentown": "ABE",
    "Alma Ata": "ALA",
    "Alor Setar": "AOR",
    "Altoona": "AOO",
    "Amarillo": "AMA",
    "Amchitka": "AHT",
    "Amman": "AMM",
    "Amritsar": "ATQ",
    "Amsterdam": "AMS",
    "Amsterdam, Schiphol Airport": "SPL",
    "Baghdad, Al Muthana": "BGW",
    "Baghdad, Saddam International": "SDA",
    "Bahrain": "BAH",
    "Bakersfield": "BFL",
    "Bali Island, Denpasar": "DPS",
    "Balmaceda": "BBA",
    "Baltimore": "BWI",
    "Baltimore, Gl. Martin": "MTN",
    "Bamako": "BKO",
    "Bandar Abbas": "BND",
    "Bandar Seri Begawan": "BWN",
    "Bangalore": "BLR",
    "Bangkok": "BKK",
    "Bangor": "BGR",
    "Bangui": "BGF",
    "Banjul": "BJL",
    "Baotou": "BAV",
    "Barbados": "BGI",
    "Barcelona": "BCN",
    "Barcelona (Venezuela)": "BLA",
    "Bardufoss": "BDU",
    "Bari": "BRI",
    "Barinas": "BNS",
    "Barquisimeto": "BRM",
    "Barranquilla": "BAQ",
    "Barrow": "BRW",
    "Basle": "BSL",
    "Basra": "BSR",
    "Bastia": "BIA",
    "Baton Rouge": "BTR",
    "Battle Creek": "BTL",
    "Bay City/Saginaw": "MBS",
    "Beaumont": "BPT",
    "Beaver": "WBQ",
    "Beef Island, Tortola": "EIS",
    "Beijing": "BJS",
    "Beijing, Nanyuan Airport": "NAY",
    "Beira": "BEW",
    "Beirut": "BEY",
    "Belem": "BEL",
    "Belfast": "BFS",
    "Belfast, Belfast City": "BHD",
    "Belgrade": "BEG",
    "Belize": "BZE",
    "Belize, Municipal": "TZA",
    "Bellingham": "BLI",
    "Belo Horizonte": "BHZ",
    "Benghazi": "BEN",
    "Bergen": "BGO",
    "Berlin": "BER",
    "Berlin, Schonefeld": "SXF",
    "Berlin, Tegel": "TXL",
    "Berlin, Tempelhof": "THF",
    "Bermuda": "BDA",
    "Bern": "BRN",
    "Bethel": "BET",
    "Bettles": "BTT",
    "Cairns": "CNS",
    "Cairo": "CAI",
    "Cajamarca": "CJA",
    "Calama": "CJC",
    "Calcutta": "CCU",
    "Calgary": "YYC",
    "Cali": "CLO",
    "Calicut": "CCJ",
    "Calvi": "CLY",
    "Cambridge Bay": "YCB",
    "Campo Grande": "CGR",
    "Canaima": "CAJ",
    "Cancun": "CUN",
    "Cape Girardeau": "CGI",
    "Cape Town": "CPT",
    "Caracas": "CCS",
    "Cardiff": "CWL",
    "Carlsbad": "CNM",
    "Cartagena": "CTG",
    "Carupano": "CUP",
    "Casablanca": "CAS",
    "Casablanca, Mohamed V": "CMN",
    "Casablanca, Anfa": "CAS",
    "Casper": "CPR",
    "Catania": "CTA",
    "Cayenne": "CAY",
    "Cebu": "CEB",
    "Cedar City": "CDC",
    "Cedar Rapids / Iowa City": "CID",
    "Chachapoyas": "CHH",
    "Chalkyitsik": "CIK",
    "Champaign": "CMI",
    "Changchun": "CGQ",
    "Changsha": "CSX",
    "Charleston": "CHS",
    "Charlotte": "CLT",
    "Chattanooga": "CHA",
    "Chefornak": "CYF",
    "Cheju": "CJU",
    "Chengdu": "CTU",
    "Chetumal": "CTM",
    "Chevak": "VAK",
    "Chiang Mai": "CNX",
    "Chicago": "CHI",
    "Chicago, Merill C. Meigs": "CGX",
    "Chicago, Midway": "MDW",
    "Chicago, O’Hare": "ORD",
    "Chichenitza": "CZA",
    "Chiclayo": "CIX",
    "Chico": "CIC",
    "Chignik": "KCL",
    "Chihuahua": "CUU",
    "Chisholm": "HIB",
    "Chittagong": "CGP",
    "Dakar": "DKR",
    "Dalaman": "DLM",
    "Dalian": "DLC",
    "Dallas/Ft. Worth": "DFW",
    "Dallas, Love Field": "DAL",
    "Damascus": "DAM",
    "Danville": "DNV",
    "Dar Es Salaam": "DAR",
    "Darwin": "DRW",
    "Davao": "DVO",
    "Dayton": "DAY",
    "Daytona Beach": "DAB",
    "Decatur": "DEC",
    "Deer Lake": "YDF",
    "Delhi": "DEL",
    "Delta": "DTA",
    "Denver": "DEN",
    "Des Moines": "DSM",
    "Detroit": "DTT",
    "Detroit City": "DET",
    "Detroit, Willow Run": "YIP",
    "Dhahran": "DHA",
    "East London": "ELS",
    "East Midlands": "EMA",
    "Easter Island": "IPC",
    "Edinburgh": "EDI",
    "Edmonton": "YEA",
    "Edmonton, Albert Int’l": "YEG",
    "Edmonton, Municipal": "YXD",
    "Edmonton, Namao Field": "YED",
    "Eek": "EEK",
    "Eglin Afb/Valparaiso": "VPS",
    "Eindhoven": "EIN",
    "El Paso": "ELP",
    "El Salvador": "ESR",
    "Elat": "ETH",
    "Elko": "EKO",
    "Ely": "ELY",
    "Fairbanks": "FAI",
    "Fall River, New Bedford": "EWB",
    "False Pass": "KFP",
    "Fargo": "FAR",
    "Faro": "FAO",
    "Fayetteville": "FAY",
    "Fez": "FEZ",
    "Fillmore": "FIL",
    "Flagstaff": "FLG",
    "Flamingo": "FLM",
    "Florence": "FLO",
    "Florence (Italy)": "FLR",
    "Florence (SC)": "FLO",
    "Fortaleza": "FOR",
    "Frankfurt": "FRA",
    "Frankfurt Hahn": "HHN",
    "Frederick": "FDK",
    "Freeport": "FPO",
    "Fremantle": "FTE",
    "Fresno": "FAT",
    "Friedrichshafen": "FDH",
    "Ft. Lauderdale": "FLL",
    "Ft. Myers": "RSW",
    "Ft. Walton Beach": "VPS",
    "Ft. Wayne": "FWA",
    "Fukue": "FUJ",
    "Fukuoka": "FUK",
    "Funchal": "FNC",
    "Fuyang": "FUG",
    "Gaborone": "GBE",
    "Gainesville": "GNV",
    "Galapagos": "GPS",
    "Galway": "GWY",
    "Gander": "YQX",
    "Garden City": "GCK",
    "Garoe": "GGR",
    "Gary": "GYY",
    "Gaya": "GAY",
    "Gaziantep": "GZT",
    "Geneva": "GVA",
    "Genoa": "GOA",
    "Georgetown": "GEO",
    "Gibraltar": "GIB",
    "Glasgow": "GLA",
    "Glen Falls": "GFL",
    "Glen Innes": "GLI",
    "Glenview": "NBU",
    "Gold Coast": "OOL",
    "Golmud": "GOQ",
    "Goose Bay": "YYR",
    "Grand Canyon": "GCN",
    "Grand Rapids": "GRR",
    "Grand Turk Island": "GDT",
    "Granite City": "GRI",
    "Graz": "GRZ",
    "Green Bay": "GRB",
    "Greenbrier": "LWB",
    "Greensboro": "GSO",
    "Greenville": "GLH",
    "Guadalajara": "GDL",
    "Guam": "GUM",
    "Guangzhou": "CAN",
    "Guarulhos": "GRU",
    "Gulfport/Biloxi": "GPT",
    "Gustavus": "GST",
    "Guatemala": "GUA",
    "Guayaquil": "GYE",
    "Gwangju": "KWJ",
    "Gwadar": "GWD",
    "Gyandzha": "KVD",
    "Gyor": "QGY",
    "Haifa": "HFA",
    "Haikou": "HAK",
    "Hail": "HAS",
    "Halifax": "YHZ",
    "Hamburg": "HAM",
    "Hamburg (Finkenwerder)": "XFW",
    "Hamilton": "HLZ",
    "Hana": "HNM",
    "Hanamaki": "HNA",
    "Hancock": "CMX",
    "Hangzhou": "HGH",
    "Hanover": "HAJ",
    "Harare": "HRE",
    "Harrisburg": "MDT",
    "Harrison": "HRO",
    "Hartford": "BDL",
    "Hastings": "HSI",
    "Hat Yai": "HDY",
    "Havana": "HAV",
    "Hayward": "HWD",
    "Healy Lake": "HKB",
    "Helsinki": "HEL",
    "Hermosillo": "HMO",
    "Hervey Bay": "HVB",
    "Hibbing": "HIB",
    "Hilton Head": "HHH",
    "Hiroshima": "HIJ",
    "Hobart": "HBA",
    "Holguin": "HOG",
    "Honiara": "HIR",
    "Hong Kong": "HKG",
    "Honolulu": "HNL",
    "Horta": "HOR",
    "Houston": "IAH",
    "Hualien": "HUN",
    "Huanuco": "HUU",
    "Huntsville": "HSV",
    "Hurghada": "HRG",
    "Hyannis": "HYA",
    "Iasi": "IAS",
    "Ibiza": "IBZ",
    "Iguassu Falls": "IGU",
    "Ilheus": "IOS",
    "Imperatriz": "IMP",
    "Indianapolis": "IND",
    "Innsbruck": "INN",
    "Iquitos": "IQT",
    "Irkutsk": "IKT",
    "Isfahan": "IFN",
    "Islamabad": "ISB",
    "Istanbul": "IST",
    "Ithaca": "ITH",
    "Ivano-Frankovsk": "IFO",
    "Izmir": "ADB",
    "Jackson": "JAC",
    "Jacksonville": "JAX",
    "Jakarta": "JKT",
    "Jamestown": "JMS",
    "Jeddah": "JED",
    "Jersey": "JER",
    "Jiangmen": "JMJ",
    "Jinan": "TNA",
    "Jinghong": "JHG",
    "Jodhpur": "JDH",
    "Johannesburg": "JNB",
    "Joinville": "JOI",
    "Juba": "JUB",
    "Juneau": "JNU",
    "Kabul": "KBL",
    "Kahului": "OGG",
    "Kailua-Kona": "KOA",
    "Kalamazoo": "AZO",
    "Kalispell": "FCA",
    "Kampala": "KLA",
    "Kandy": "KDW",
    "Kano": "KAN",
    "Kapalua": "JHM",
    "Karachi": "KHI",
    "Kars": "KSY",
    "Kathmandu": "KTM",
    "Katowice": "KTW",
    "Kaunas": "KUN",
    "Kavala": "KVA",
    "Kayseri": "ASR",
    "Kefallinia": "EFL",
    "Kelowna": "YLW",
    "Kemijarvi": "KEM",
    "Kenai": "ENA",
    "Ketchikan": "KTN",
    "Khartoum": "KRT",
    "Kherson": "KHE",
    "Kiev": "KBP",
    "Kigali": "KGL",
    "Kilimanjaro": "JRO",
    "Kingston": "KIN",
    "Kinshasa": "FIH",
    "Kirkenes": "KKN",
    "Kiruna": "KRN",
    "Kisumu": "KIS",
    "Kitakyushu": "KKJ",
    "Knoxville": "TYS",
    "Kodiak": "ADQ",
    "Kona": "KOA",
    "Konya": "KYA",
    "Kos": "KGS",
    "Kosice": "KSC",
    "Kota Kinabalu": "BKI",
    "Kotzebue": "OTZ",
    "Krabi": "KBV",
    "Krakow": "KRK",
    "Krasnodar": "KRR",
    "Kuala Lumpur": "KUL",
    "Kuantan": "KUA",
    "Kuching": "KCH",
    "Kumamoto": "KMJ",
    "Kunming": "KMG",
    "Kuopio": "KUO",
    "Kuwait": "KWI",
    "Kyzyl": "KYZ",
    "La Crosse": "LSE",
    "La Paz": "LAP",
    "La Plata": "LPG",
    "La Rochelle": "LRH",
    "Lagos": "LOS",
    "Lahore": "LHE",
    "Lajes": "TER",
    "Lampang": "LPT",
    "Lands End": "LEQ",
    "Lansing": "LAN",
    "Laramie": "LAR",
    "Larnaca": "LCA",
    "Las Palmas": "LPA",
    "Las Vegas": "LAS",
    "Latrobe": "LBE",
    "Launceston": "LST",
    "Lautoka": "NAN",
    "Lazaro Cardenas": "LZC",
    "Le Puy": "LPY",
    "Leeds": "LBA",
    "Leon": "LEN",
    "Lethbridge": "YQL",
    "Lianyungang": "LYG",
    "Lihue": "LIH",
    "Lilongwe": "LLW",
    "Lima": "LIM",
    "Limoges": "LIG",
    "Lincoln": "LNK",
    "Linkoping": "LPI",
    "Lisbon": "LIS",
    "Liverpool": "LPL",
    "Livingstone": "LVI",
    "Ljubljana": "LJU",
    "Lome": "LFW",
    "Londonderry": "LDY",
    "London": "LON",
    "London City": "LCY",
    "London Gatwick": "LGW",
    "London Heathrow": "LHR",
    "London Luton": "LTN",
    "London Stansted": "STN",
    "Long Beach": "LGB",
    "Longview": "GGG",
    "Lopburi": "LRI",
    "Loreto": "LTO",
    "Los Angeles": "LAX",
    "Louisville": "SDF",
    "Luanda": "LAD",
    "Lubbock": "LBB",
    "Lucknow": "LKO",
    "Lusaka": "LUN",
    "Luxembourg": "LUX",
    "Lvov": "LWO",
    "Lyon": "LYS",
    "Maastricht": "MST",
    "Macau": "MFM",
    "Macon": "MCN",
    "Madison": "MSN",
    "Madrid": "MAD",
    "Madurai": "IXM",
    "Mahe Island": "SEZ",
    "Mahlapye": "MFA",
    "Mahon": "MAH",
    "Maiduguri": "MIU",
    "Majuro": "MAJ",
    "Malabo": "SSG",
    "Malaga": "AGP",
    "Malang": "MLG",
    "Malatya": "MLX",
    "Male": "MLE",
    "Malmo": "MMX",
    "Managua": "MGA",
    "Manaus": "MAO",
    "Manchester": "MAN",
    "Manila": "MNL",
    "Manzini": "MTS",
    "Maputo": "MPM",
    "Maracaibo": "MAR",
    "Marrakech": "RAK",
    "Marsa Alam": "RMF",
    "Marseille": "MRS",
    "Mataram": "AMI",
    "Mazatlan": "MZT",
    "Medan": "MES",
    "Medellin": "MDE",
    "Medina": "MED",
    "Melbourne": "MEL",
    "Memphis": "MEM",
    "Merida": "MID",
    "Mexico City": "MEX",
    "Miami": "MIA",
    "Mianyang": "MIG",
    "Milan": "MIL",
    "Milan Malpensa": "MXP",
    "Milwaukee": "MKE",
    "Minneapolis": "MSP",
    "Minsk": "MSQ",
    "Miri": "MYY",
    "Missoula": "MSO",
    "Mobile": "MOB",
    "Modesto": "MOD",
    "Moenchengladbach": "MGL",
    "Monaco": "MCM",
    "Monroe": "MLU",
    "Monterrey": "MTY",
    "Montevideo": "MVD",
    "Montgomery": "MGM",
    "Montpellier": "MPL",
    "Montreal": "YUL",
    "Montrose": "MTJ",
    "Moroni": "HAH",
    "Moscow": "MOW",
    "Mosul": "OSM",
    "Mumbai": "BOM",
    "Munich": "MUC",
    "Murcia": "MJV",
    "Muskogee": "MKO",
    "Mwanza": "MWZ",
    "Mykonos": "JMK",
    "Nairobi": "NBO",
    "Nantes": "NTE",
    "Naples": "NAP",
    "Narvik": "NVK",
    "Nashville": "BNA",
    "Natal": "NAT",
    "Ndola": "NLA",
    "New Orleans": "MSY",
    "New York": "JFK",
    "Niamey": "NIM",
    "Nice": "NCE",
    "Nicosia": "NIC",
    "Nouakchott": "NKC",
    "Nuremburg": "NUE",
    "Odessa": "ODS",
    "Orlando": "MCO",
    "Osaka": "OSA",
    "Oslo": "OSL",
    "Palermo": "PMO",
    "Paris": "PAR",
    "Perth": "PER",
    "Philadelphia": "PHL",
    "Phoenix": "PHX",
    "Pittsburgh": "PIT",
    "Portland": "PDX",
    "Prague": "PRG",
    "Providence": "PVD",
    "Punta Cana": "PUJ",
    "Quebec": "YQB",
    "Reykjavik": "KEF",
    "Riyadh": "RUH",
    "Rome": "FCO",
    "San Diego": "SAN",
    "San Francisco": "SFO",
    "San Jose": "SJC",
    "San Juan": "SJU",
    "Santiago": "SCL",
    "Santo Domingo": "SDQ",
    "Sao Paulo": "GRU",
    "Seattle": "SEA",
    "Seoul": "ICN",
    "Shanghai": "PVG",
    "Singapore": "SIN",
    "Stockholm": "ARN",
    "Sydney": "SYD",
    "Tokyo": "HND",
    "Toronto": "YYZ",
    "Venice": "VCE",
    "Vienna": "VIE",
    "Warsaw": "WAW",
    "Washington": "IAD",
    "Zurich": "ZRH"
};

exports. getAirportCode = (location) => {
    return airports[location] || "Airport not found";
};

module.exports = airports;